package lt.dndfan.dndhelper.service.dnd.definition

object DefinitionBuilderService {
    const val ABILITY_SCORE = "AbilityScoreDefinitionBuilder"
    const val BACKGROUND = "BackgroundDefinitionBuilder"
    const val CLASS_DESCRIPTION = "ClassDescriptionDefinitionBuilder"
    const val CLASS = "ClassDefinitionBuilder"
    const val CONDITION = "ConditionDefinitionBuilder"
    const val DAMAGE_TYPE = "DamageTypeDefinitionBuilder"
    const val EQUIPMENT = "EquipmentDefinitionBuilder"
    const val EQUIPMENT_CATEGORY = "EquipmentCategoryDefinitionBuilder"
    const val FEATURE = "FeatureDefinitionBuilder"
    const val LANGUAGE = "LanguageDefinitionBuilder"
    const val CLASS_LEVEL = "LevelDefinitionBuilder"
    const val MAGIC_SCHOOL = "MagicSchoolDefinitionBuilder"
    const val MONSTER = "MonsterDefinitionBuilder"
    const val PROFICIENCY = "ProficiencyDefinitionBuilder"
    const val RACE = "RaceDefinitionBuilder"
    const val SKILL = "SkillDefinitionBuilder"
    const val SPELLCASTING = "SpellcastingDefinitionBuilder"
    const val SPELL = "SpellDefinitionBuilder"
    const val STARTING_EQUIPMENT = "StartingEquipmentDefinitionBuilder"
    const val SUBCLASS = "SubclassDefinitionBuilder"
    const val SUBRACE = "SubraceDefinitionBuilder"
    const val TRAIT = "TraitDefinitionBuilder"
    const val WEAPON_PROPERTY = "WeaponPropertyDefinitionBuilder"
}